name: reviewdog
on: pull_request
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: 'src/**/*.{js,ts,jsx,tsx}'
